# --------------------------------------------------------------------
# makefile for BBStyle - gcc (mingw)
#

TOP = ../..

BIN = BBStyle.dll
OBJ = BBStyle.obj
SYSLIBS = -lshlwapi
INSTALL_FILES = $(BIN) BBStyle.html
INSTALL_IF_NEW = resource.rc

include $(TOP)/build/makefile.inc
