# --------------------------------------------------------------------
# makefile for BBRecycleBin - gcc (mingw)
#

TOP = ../..

BIN = bbRecycleBin.dll
OBJ = bbRecycleBin.obj
SYSLIBS = -lshlwapi
INSTALL_FILES = $(BIN) readme.txt
INSTALL_IF_NEW = bbRecycleBin.rc

include $(TOP)/build/makefile.inc
