# --------------------------------------------------------------------
# makefile for bbSlit - gcc (mingw)
#

TOP = ../..

BIN = bbSlit.dll
OBJ = bbSlit.obj bbPlugin.obj
INSTALL_FILES = $(BIN) readme.txt
INSTALL_IF_NEW = bbSlit.rc

include $(TOP)/build/makefile.inc
