# --------------------------------------------------------------------
# makefile for bbAnalog - gcc (mingw)

TOP = ../..

BIN = bbAnalog.dll
OBJ = bbAnalog.obj bbPlugin.obj
INSTALL_FILES = $(BIN) readme.txt
INSTALL_IF_NEW = bbAnalog.rc

include $(TOP)/build/makefile.inc
