# --------------------------------------------------------------------
# makefile for bsetshell.exe
#

TOP = ../..

BIN = bsetshell.exe
OBJ = bsetshell.obj resource.res
INSTALL_FILES = $(BIN)

include $(TOP)/build/makefile.inc
