# --------------------------------------------------------------------
# makefile for bbWorkspaceWheel - gcc (mingw)

TOP = ../..

OBJ = bbWorkspaceWheel.obj
BIN = bbWorkspaceWheel.dll
INSTALL_FILES = $(BIN) readme.txt

include $(TOP)/build/makefile.inc
