# --------------------------------------------------------------------
# makefile for bbKeys - gcc (mingw)
#

TOP = ../..

BIN = bbKeys.dll
OBJ = bbKeys.obj
INSTALL_FILES = $(BIN) readme.txt
INSTALL_IF_NEW = bbKeys.rc

include $(TOP)/build/makefile.inc
