# --------------------------------------------------------------------
# makefile for bbColor3dc - gcc (mingw)

TOP = ../..

BIN = bbColor3dc.dll
OBJ = bbColor3dc.obj
INSTALL_FILES = $(BIN) readme.txt

include $(TOP)/build/makefile.inc
